/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertEvent {
  'id' : AlertId,
  'sensorName' : string,
  'value' : number,
  'acknowledged' : boolean,
  'timestamp' : Timestamp,
  'severity' : string,
  'machineId' : MachineId,
  'machineName' : string,
}
export type AlertId = string;
export interface AlertThreshold {
  'id' : string,
  'sensorName' : string,
  'warnLevel' : number,
  'sensorId' : SensorId,
  'criticalLevel' : number,
  'machineId' : MachineId,
}
export interface Machine {
  'id' : MachineId,
  'status' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'machineType' : string,
}
export type MachineId = string;
export interface ProductionPoint {
  'count' : bigint,
  'timestamp' : Timestamp,
  'machineId' : MachineId,
}
export interface Sensor {
  'id' : SensorId,
  'sensorName' : string,
  'refreshInterval' : bigint,
  'createdAt' : Timestamp,
  'unit' : string,
  'enabled' : boolean,
  'machineId' : MachineId,
}
export type SensorId = string;
export interface SensorReading {
  'sensorName' : string,
  'value' : number,
  'sensorId' : SensorId,
  'timestamp' : Timestamp,
  'machineId' : MachineId,
}
export type Timestamp = bigint;
export interface WearRecord {
  'wearPercent' : number,
  'timestamp' : Timestamp,
  'machineId' : MachineId,
}
export interface _SERVICE {
  'acknowledgeAlert' : ActorMethod<
    [AlertId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addAlertEvent' : ActorMethod<
    [MachineId, string, string, number, string],
    { 'ok' : AlertEvent } |
      { 'err' : string }
  >,
  'addMachine' : ActorMethod<
    [string, string, string],
    { 'ok' : Machine } |
      { 'err' : string }
  >,
  'addSensor' : ActorMethod<
    [MachineId, string, string, bigint],
    { 'ok' : Sensor } |
      { 'err' : string }
  >,
  'clearAlerts' : ActorMethod<[], undefined>,
  'deleteMachine' : ActorMethod<
    [MachineId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteSensor' : ActorMethod<
    [SensorId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAlertEvents' : ActorMethod<[bigint], Array<AlertEvent>>,
  'getAlertThresholds' : ActorMethod<[MachineId], Array<AlertThreshold>>,
  'getMachines' : ActorMethod<[], Array<Machine>>,
  'getProductionHistory' : ActorMethod<
    [MachineId, bigint],
    Array<ProductionPoint>
  >,
  'getSensorReadings' : ActorMethod<
    [MachineId, string, bigint],
    Array<SensorReading>
  >,
  'getSensorsForMachine' : ActorMethod<[MachineId], Array<Sensor>>,
  'getTotalProduction' : ActorMethod<[], bigint>,
  'getWearHistory' : ActorMethod<[MachineId, bigint], Array<WearRecord>>,
  'recordProduction' : ActorMethod<
    [MachineId, bigint],
    { 'ok' : ProductionPoint } |
      { 'err' : string }
  >,
  'recordSensorReading' : ActorMethod<
    [SensorId, MachineId, string, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordWear' : ActorMethod<
    [MachineId, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setAlertThreshold' : ActorMethod<
    [MachineId, SensorId, string, number, number],
    { 'ok' : AlertThreshold } |
      { 'err' : string }
  >,
  'updateMachine' : ActorMethod<
    [MachineId, string, string, string],
    { 'ok' : Machine } |
      { 'err' : string }
  >,
  'updateSensor' : ActorMethod<
    [SensorId, string, string, bigint, boolean],
    { 'ok' : Sensor } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];