/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertId = IDL.Text;
export const MachineId = IDL.Text;
export const Timestamp = IDL.Int;
export const AlertEvent = IDL.Record({
  'id' : AlertId,
  'sensorName' : IDL.Text,
  'value' : IDL.Float64,
  'acknowledged' : IDL.Bool,
  'timestamp' : Timestamp,
  'severity' : IDL.Text,
  'machineId' : MachineId,
  'machineName' : IDL.Text,
});
export const Machine = IDL.Record({
  'id' : MachineId,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'machineType' : IDL.Text,
});
export const SensorId = IDL.Text;
export const Sensor = IDL.Record({
  'id' : SensorId,
  'sensorName' : IDL.Text,
  'refreshInterval' : IDL.Nat,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'enabled' : IDL.Bool,
  'machineId' : MachineId,
});
export const AlertThreshold = IDL.Record({
  'id' : IDL.Text,
  'sensorName' : IDL.Text,
  'warnLevel' : IDL.Float64,
  'sensorId' : SensorId,
  'criticalLevel' : IDL.Float64,
  'machineId' : MachineId,
});
export const ProductionPoint = IDL.Record({
  'count' : IDL.Nat,
  'timestamp' : Timestamp,
  'machineId' : MachineId,
});
export const SensorReading = IDL.Record({
  'sensorName' : IDL.Text,
  'value' : IDL.Float64,
  'sensorId' : SensorId,
  'timestamp' : Timestamp,
  'machineId' : MachineId,
});
export const WearRecord = IDL.Record({
  'wearPercent' : IDL.Float64,
  'timestamp' : Timestamp,
  'machineId' : MachineId,
});

export const idlService = IDL.Service({
  'acknowledgeAlert' : IDL.Func(
      [AlertId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addAlertEvent' : IDL.Func(
      [MachineId, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : AlertEvent, 'err' : IDL.Text })],
      [],
    ),
  'addMachine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Machine, 'err' : IDL.Text })],
      [],
    ),
  'addSensor' : IDL.Func(
      [MachineId, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : Sensor, 'err' : IDL.Text })],
      [],
    ),
  'clearAlerts' : IDL.Func([], [], []),
  'deleteMachine' : IDL.Func(
      [MachineId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteSensor' : IDL.Func(
      [SensorId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAlertEvents' : IDL.Func([IDL.Nat], [IDL.Vec(AlertEvent)], ['query']),
  'getAlertThresholds' : IDL.Func(
      [MachineId],
      [IDL.Vec(AlertThreshold)],
      ['query'],
    ),
  'getMachines' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
  'getProductionHistory' : IDL.Func(
      [MachineId, IDL.Nat],
      [IDL.Vec(ProductionPoint)],
      ['query'],
    ),
  'getSensorReadings' : IDL.Func(
      [MachineId, IDL.Text, IDL.Nat],
      [IDL.Vec(SensorReading)],
      ['query'],
    ),
  'getSensorsForMachine' : IDL.Func([MachineId], [IDL.Vec(Sensor)], ['query']),
  'getTotalProduction' : IDL.Func([], [IDL.Nat], ['query']),
  'getWearHistory' : IDL.Func(
      [MachineId, IDL.Nat],
      [IDL.Vec(WearRecord)],
      ['query'],
    ),
  'recordProduction' : IDL.Func(
      [MachineId, IDL.Nat],
      [IDL.Variant({ 'ok' : ProductionPoint, 'err' : IDL.Text })],
      [],
    ),
  'recordSensorReading' : IDL.Func(
      [SensorId, MachineId, IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordWear' : IDL.Func(
      [MachineId, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setAlertThreshold' : IDL.Func(
      [MachineId, SensorId, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Variant({ 'ok' : AlertThreshold, 'err' : IDL.Text })],
      [],
    ),
  'updateMachine' : IDL.Func(
      [MachineId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Machine, 'err' : IDL.Text })],
      [],
    ),
  'updateSensor' : IDL.Func(
      [SensorId, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : Sensor, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertId = IDL.Text;
  const MachineId = IDL.Text;
  const Timestamp = IDL.Int;
  const AlertEvent = IDL.Record({
    'id' : AlertId,
    'sensorName' : IDL.Text,
    'value' : IDL.Float64,
    'acknowledged' : IDL.Bool,
    'timestamp' : Timestamp,
    'severity' : IDL.Text,
    'machineId' : MachineId,
    'machineName' : IDL.Text,
  });
  const Machine = IDL.Record({
    'id' : MachineId,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'machineType' : IDL.Text,
  });
  const SensorId = IDL.Text;
  const Sensor = IDL.Record({
    'id' : SensorId,
    'sensorName' : IDL.Text,
    'refreshInterval' : IDL.Nat,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'enabled' : IDL.Bool,
    'machineId' : MachineId,
  });
  const AlertThreshold = IDL.Record({
    'id' : IDL.Text,
    'sensorName' : IDL.Text,
    'warnLevel' : IDL.Float64,
    'sensorId' : SensorId,
    'criticalLevel' : IDL.Float64,
    'machineId' : MachineId,
  });
  const ProductionPoint = IDL.Record({
    'count' : IDL.Nat,
    'timestamp' : Timestamp,
    'machineId' : MachineId,
  });
  const SensorReading = IDL.Record({
    'sensorName' : IDL.Text,
    'value' : IDL.Float64,
    'sensorId' : SensorId,
    'timestamp' : Timestamp,
    'machineId' : MachineId,
  });
  const WearRecord = IDL.Record({
    'wearPercent' : IDL.Float64,
    'timestamp' : Timestamp,
    'machineId' : MachineId,
  });
  
  return IDL.Service({
    'acknowledgeAlert' : IDL.Func(
        [AlertId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addAlertEvent' : IDL.Func(
        [MachineId, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : AlertEvent, 'err' : IDL.Text })],
        [],
      ),
    'addMachine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Machine, 'err' : IDL.Text })],
        [],
      ),
    'addSensor' : IDL.Func(
        [MachineId, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : Sensor, 'err' : IDL.Text })],
        [],
      ),
    'clearAlerts' : IDL.Func([], [], []),
    'deleteMachine' : IDL.Func(
        [MachineId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteSensor' : IDL.Func(
        [SensorId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAlertEvents' : IDL.Func([IDL.Nat], [IDL.Vec(AlertEvent)], ['query']),
    'getAlertThresholds' : IDL.Func(
        [MachineId],
        [IDL.Vec(AlertThreshold)],
        ['query'],
      ),
    'getMachines' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
    'getProductionHistory' : IDL.Func(
        [MachineId, IDL.Nat],
        [IDL.Vec(ProductionPoint)],
        ['query'],
      ),
    'getSensorReadings' : IDL.Func(
        [MachineId, IDL.Text, IDL.Nat],
        [IDL.Vec(SensorReading)],
        ['query'],
      ),
    'getSensorsForMachine' : IDL.Func(
        [MachineId],
        [IDL.Vec(Sensor)],
        ['query'],
      ),
    'getTotalProduction' : IDL.Func([], [IDL.Nat], ['query']),
    'getWearHistory' : IDL.Func(
        [MachineId, IDL.Nat],
        [IDL.Vec(WearRecord)],
        ['query'],
      ),
    'recordProduction' : IDL.Func(
        [MachineId, IDL.Nat],
        [IDL.Variant({ 'ok' : ProductionPoint, 'err' : IDL.Text })],
        [],
      ),
    'recordSensorReading' : IDL.Func(
        [SensorId, MachineId, IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordWear' : IDL.Func(
        [MachineId, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setAlertThreshold' : IDL.Func(
        [MachineId, SensorId, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Variant({ 'ok' : AlertThreshold, 'err' : IDL.Text })],
        [],
      ),
    'updateMachine' : IDL.Func(
        [MachineId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Machine, 'err' : IDL.Text })],
        [],
      ),
    'updateSensor' : IDL.Func(
        [SensorId, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : Sensor, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };