/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Sensor {
    id: SensorId;
    sensorName: string;
    refreshInterval: bigint;
    createdAt: Timestamp;
    unit: string;
    enabled: boolean;
    machineId: MachineId;
}
export type Timestamp = bigint;
export interface AlertThreshold {
    id: string;
    sensorName: string;
    warnLevel: number;
    sensorId: SensorId;
    criticalLevel: number;
    machineId: MachineId;
}
export type AlertId = string;
export interface AlertEvent {
    id: AlertId;
    sensorName: string;
    value: number;
    acknowledged: boolean;
    timestamp: Timestamp;
    severity: string;
    machineId: MachineId;
    machineName: string;
}
export type MachineId = string;
export interface ProductionPoint {
    count: bigint;
    timestamp: Timestamp;
    machineId: MachineId;
}
export interface SensorReading {
    sensorName: string;
    value: number;
    sensorId: SensorId;
    timestamp: Timestamp;
    machineId: MachineId;
}
export interface Machine {
    id: MachineId;
    status: string;
    name: string;
    createdAt: Timestamp;
    machineType: string;
}
export type SensorId = string;
export interface WearRecord {
    wearPercent: number;
    timestamp: Timestamp;
    machineId: MachineId;
}
export interface backendInterface {
    acknowledgeAlert(id: AlertId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addAlertEvent(machineId: MachineId, machineName: string, sensorName: string, value: number, severity: string): Promise<{
        __kind__: "ok";
        ok: AlertEvent;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addMachine(name: string, machineType: string, status: string): Promise<{
        __kind__: "ok";
        ok: Machine;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addSensor(machineId: MachineId, sensorName: string, unit: string, refreshInterval: bigint): Promise<{
        __kind__: "ok";
        ok: Sensor;
    } | {
        __kind__: "err";
        err: string;
    }>;
    clearAlerts(): Promise<void>;
    deleteMachine(id: MachineId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteSensor(id: SensorId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAlertEvents(limit: bigint): Promise<Array<AlertEvent>>;
    getAlertThresholds(machineId: MachineId): Promise<Array<AlertThreshold>>;
    getMachines(): Promise<Array<Machine>>;
    getProductionHistory(machineId: MachineId, hours: bigint): Promise<Array<ProductionPoint>>;
    getSensorReadings(machineId: MachineId, sensorName: string, hours: bigint): Promise<Array<SensorReading>>;
    getSensorsForMachine(machineId: MachineId): Promise<Array<Sensor>>;
    getTotalProduction(): Promise<bigint>;
    getWearHistory(machineId: MachineId, hours: bigint): Promise<Array<WearRecord>>;
    recordProduction(machineId: MachineId, count: bigint): Promise<{
        __kind__: "ok";
        ok: ProductionPoint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordSensorReading(sensorId: SensorId, machineId: MachineId, sensorName: string, value: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordWear(machineId: MachineId, wearPercent: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAlertThreshold(machineId: MachineId, sensorId: SensorId, sensorName: string, warnLevel: number, criticalLevel: number): Promise<{
        __kind__: "ok";
        ok: AlertThreshold;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateMachine(id: MachineId, name: string, machineType: string, status: string): Promise<{
        __kind__: "ok";
        ok: Machine;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateSensor(id: SensorId, sensorName: string, unit: string, refreshInterval: bigint, enabled: boolean): Promise<{
        __kind__: "ok";
        ok: Sensor;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AlertEvent as _AlertEvent, AlertThreshold as _AlertThreshold, Machine as _Machine, ProductionPoint as _ProductionPoint, Sensor as _Sensor } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeAlert(arg0: AlertId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addAlertEvent(arg0: MachineId, arg1: string, arg2: string, arg3: number, arg4: string): Promise<{
        __kind__: "ok";
        ok: AlertEvent;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlertEvent(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlertEvent(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMachine(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Machine;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addMachine(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMachine(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSensor(arg0: MachineId, arg1: string, arg2: string, arg3: bigint): Promise<{
        __kind__: "ok";
        ok: Sensor;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addSensor(arg0, arg1, arg2, arg3);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSensor(arg0, arg1, arg2, arg3);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearAlerts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAlerts();
            return result;
        }
    }
    async deleteMachine(arg0: MachineId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMachine(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMachine(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSensor(arg0: SensorId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSensor(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSensor(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertEvents(arg0: bigint): Promise<Array<AlertEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertEvents(arg0);
            return result;
        }
    }
    async getAlertThresholds(arg0: MachineId): Promise<Array<AlertThreshold>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertThresholds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertThresholds(arg0);
            return result;
        }
    }
    async getMachines(): Promise<Array<Machine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMachines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMachines();
            return result;
        }
    }
    async getProductionHistory(arg0: MachineId, arg1: bigint): Promise<Array<ProductionPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionHistory(arg0, arg1);
            return result;
        }
    }
    async getSensorReadings(arg0: MachineId, arg1: string, arg2: bigint): Promise<Array<SensorReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSensorReadings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSensorReadings(arg0, arg1, arg2);
            return result;
        }
    }
    async getSensorsForMachine(arg0: MachineId): Promise<Array<Sensor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSensorsForMachine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSensorsForMachine(arg0);
            return result;
        }
    }
    async getTotalProduction(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalProduction();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalProduction();
            return result;
        }
    }
    async getWearHistory(arg0: MachineId, arg1: bigint): Promise<Array<WearRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWearHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWearHistory(arg0, arg1);
            return result;
        }
    }
    async recordProduction(arg0: MachineId, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: ProductionPoint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordProduction(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordProduction(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordSensorReading(arg0: SensorId, arg1: MachineId, arg2: string, arg3: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSensorReading(arg0, arg1, arg2, arg3);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSensorReading(arg0, arg1, arg2, arg3);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordWear(arg0: MachineId, arg1: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWear(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWear(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAlertThreshold(arg0: MachineId, arg1: SensorId, arg2: string, arg3: number, arg4: number): Promise<{
        __kind__: "ok";
        ok: AlertThreshold;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAlertThreshold(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAlertThreshold(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMachine(arg0: MachineId, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: Machine;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMachine(arg0, arg1, arg2, arg3);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMachine(arg0, arg1, arg2, arg3);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSensor(arg0: SensorId, arg1: string, arg2: string, arg3: bigint, arg4: boolean): Promise<{
        __kind__: "ok";
        ok: Sensor;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSensor(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSensor(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AlertEvent;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AlertEvent;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Machine;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Machine;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Sensor;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Sensor;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ProductionPoint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ProductionPoint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AlertThreshold;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AlertThreshold;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
